### ISSUE TITLE
Hello World test suite shows nothing for tests on web page

### ISSUE THREAD

**Issue by kotp** [exercism/groovy#51]
[Web page](http://exercism.io/exercises/groovy/hello-world/test-suite) for the Hello World exercise test suite does not show the tests.

**Comment by kytrinyx** [comment]
This is because some tests use a Specification testing library, and others use a Testing library, and the filenames are either *Spec.groovy or *Test.groovy. I'm opening up an issue so that whoever takes over the track can decide on one or the other.

For now I've fixed it in 888c9c345613acd1d84745879e695f8b5b70521b by updating the test pattern.
