### ISSUE TITLE
Update 'Run tests' section in README files to avoid comfusion

### ISSUE THREAD

**Issue by m-a-ge** [exercism/groovy#63]
There are some exercises which have auto-generated README file and require 'Run tests' section update

List of all affected exercises:
* [difference-of-squares](https://github.com/exercism/groovy/tree/master/exercises/difference-of-squares)
* [gigasecond](https://github.com/exercism/groovy/tree/master/exercises/gigasecond)
* [hamming](https://github.com/exercism/groovy/tree/master/exercises/hamming)
* [leap](https://github.com/exercism/groovy/tree/master/exercises/leap)
* [nth-prime](https://github.com/exercism/groovy/tree/master/exercises/nth-prime)
* [phone-number](https://github.com/exercism/groovy/tree/master/exercises/phone-number)
* [raindrops](https://github.com/exercism/groovy/tree/master/exercises/raindrops)
* [rna-transcription](https://github.com/exercism/groovy/tree/master/exercises/rna-transcription)
* [robot-name](https://github.com/exercism/groovy/tree/master/exercises/robot-name)
* [roman-numerals](https://github.com/exercism/groovy/tree/master/exercises/roman-numerals)

In correct version of README file exercise specific test Spec file should be mentioned ([example](https://github.com/exercism/groovy/tree/master/exercises/grains))

**Comment by kytrinyx** [comment]
@m-a-ge I am tweaking Configlet so that we can regenerate all the READMEs with the correct filename. See https://github.com/exercism/configlet/pull/48

Once this is merged and a release is cut, we can update the readme template (https://github.com/exercism/groovy/blob/master/config/exercise_readme.go.tmpl) to directly include the text that is currently in the readme insert (https://github.com/exercism/groovy/blob/master/docs/EXERCISE_README_INSERT.md).

We will be able to generate the command to run the tests in the template:

```
$ groovy ./{{ .Spec.MixedCaseName }}Spec.groovy
```

So we can delete the readme insert, and put all of it directly into the template like this.
```
{{- with .TrackInsert }}
{{ . }}
{{ end }}
```

**Comment by m-a-ge** [comment]
@kytrinyx, thanks a lot for explanation. Looks like I've missed it.
I should read more about it

**Comment by kytrinyx** [comment]
There's detailed information here: https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md If anything is confusing, please let me know so I can update it!
